services:
  - type: web
    name: bau-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    plan: free
    rootDir: backend

  - type: web
    name: bau-frontend
    env: static
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    rootDir: frontend
